/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 .\public\models\WawaOffice.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/WawaOffice.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['01_block'].geometry} material={materials.paintingDiffA} position={[-0.1, -0.1, -0.1]} />
      <mesh geometry={nodes['02_block'].geometry} material={materials.paintingDiff} position={[-0.1, 2.04, -2.28]} />
      <mesh geometry={nodes['03_block'].geometry} material={materials.matUp} position={[-2.28, 4.19, -2.28]} rotation={[0, 1.57, 0]} />
      <mesh geometry={nodes['02_block002'].geometry} material={materials['1Bt']} position={[-1.52, 3.11, -1.09]} />
      <mesh geometry={nodes['02_block003'].geometry} material={materials['3Bt']} position={[-1.52, 3.73, -1.09]} />
    </group>
  )
}

useGLTF.preload('/WawaOffice.glb')
